# .goreleaser.yaml
project_name: outputbuddy

before:
  hooks:
    - go mod tidy

builds:
  - id: outputbuddy
    main: ./outputbuddy.go
    binary: outputbuddy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.VERSION={{.Version}}
    # Skip certain combinations
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - 'Merge pull request'
      - 'Merge branch'

release:
  github:
    owner: zmunro
    name: outputbuddy
  prerelease: auto
  header: |
    ## outputbuddy v{{ .Version }}

    ### Installation

    #### Using Homebrew
    ```bash
    brew tap zmunro/outputbuddy
    brew install outputbuddy
    ```

    #### Using go install
    ```bash
    go install github.com/zmunro/outputbuddy@v{{ .Version }}
    ```

    #### Direct Download
    Download the appropriate binary for your platform from the assets below.

# Announce releases
announce:
  skip: false
